config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root                            to: 'home#index'
    get 'index',                    to: 'home#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: [:show] do
      collection do
        get :search
      end
    end
    resources :categories,          only: [:show]
    get 'cart',                     to: 'orders#edit'
    patch 'cart',                   to: 'orders#update'
    resources :line_items,          only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_types_decorator.rb
Spree::OptionType.class_eval do
  scope :colors, -> { find_by(presentation: 'Color').option_values }
  scope :sizes, -> { find_by(presentation: 'Size').option_values }
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  def related_products
    Spree::Product.in_taxons(taxons).includes(master: [:default_price, :images]).distinct.where.not(id: id)
  end

  scope :filter_by_taxon, -> (taxon) { in_taxon(taxon).includes(master: [:default_price, :images]) }

  scope :filter_by_option_value, -> (option) do
    joins(variants: :option_values).where(spree_option_values: { name: option }).distinct
  end

  def self.search(search)
    includes(master: [:default_price, :images]).
      where(['name LIKE ? OR description LIKE ?', "%#{sanitize_sql_like(search)}%", "%#{sanitize_sql_like(search)}%"]).distinct
  end

  scope :sort_in_order, -> (sort) do
    case sort
    when "arrivals_desc"
      reorder(available_on: :desc)
    when "arrivals_asc"
      reorder(available_on: :asc)
    when "high_price"
      unscope(:order).descend_by_master_price
    when "low_price"
      unscope(:order).ascend_by_master_price
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  helper_method :count_products_with_option_value

  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.includes(:root)
    @option_types = Spree::OptionType.all
    @products =
      if params[:option].present?
        Spree::Product.filter_by_taxon(@taxon).filter_by_option_value(params[:option])
      elsif params[:sort].present?
        Spree::Product.filter_by_taxon(@taxon).sort_in_order(params[:sort])
      else
        Spree::Product.filter_by_taxon(@taxon).order(available_on: :desc)
      end
  end

  private

  def count_products_with_option_value(option_value)
    Spree::Product.includes(variants: :option_values).in_taxon(@taxon).where(spree_option_values: { name: option_value.name }).count
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAX_NEW_PRODUCTS = 8

  def index
    @new_products = Spree::Product.includes(master: [:default_price, :images]).order(available_on: :desc).limit(MAX_NEW_PRODUCTS)
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def create
    order = current_order(create_order_if_necessary: true)
    authorize! :update, order, cookies.signed[:guest_token]

    variant = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].to_i

    if !quantity.between?(1, 2_147_483_647)
      order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end

    begin
      @line_item = order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => e
      order.errors.add(:base, e.record.errors.full_messages.join(","))
    end

    if order.errors.any?
      flash[:error] = order.errors.full_messages.join(",")
      redirect_back_or_default(spree.root_path)
      return
    else
      redirect_to potepan_cart_path
    end
  end

  def destroy
    item = Spree::LineItem.find(params[:id])
    item.order.contents.remove_line_item(item)
    redirect_to potepan_cart_path
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def edit
    @order = current_order || Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
  end

  def update
    @order = Spree::Order.find_by(number: params[:number])
    @order.contents.update_cart(order_params)
    redirect_to potepan_cart_path
  end

  def order_params
    params.require(:order).permit(line_items_attributes: [:id, :quantity])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_RELATED_PRODUCTS = 4

  def show
    @product = Spree::Product.find(params[:id])
    @related_products = @product.related_products.limit(MAX_RELATED_PRODUCTS)
  end

  def search
    @search_word = params[:search]
    @products = Spree::Product.search(@search_word)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li><span><a data-toggle="modal" href='#login'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span></li>
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <%= form_tag(search_potepan_products_path, id: "form01", method: "get", enforce_utf8: false) do %>
                    <span class="input-group">
                      <%= text_field_tag :search, "", class: "form-control", placeholder: "Search…", aria_describedby: "basic-addon2" %>
                      <button><span class="input-group-addon" id="basic-addon2" onclick="this.form.submit()">検索</span></button>
                    </span>
                  <% end %>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <%= link_to potepan_cart_path do %>
                <i class="fa fa-shopping-cart"></i>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("img/logo.png", :alt => "logo"), potepan_root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Home', potepan_root_path %></li>
          <li class="dropdown megaDropMenu">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products Grid View</li>
                  <li>
                    <%= link_to "Products Sidebar Left", potepan_product_grid_left_sidebar_path %>
                  </li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products List View</li>
                  <li>
                    <%= link_to "Products Sidebar Left", potepan_product_list_left_sidebar_path %>
                  </li>
                  <li class="listHeading">Others</li>
                  <li>
                    <%= link_to "Single Product", potepan_single_product_path %>
                  </li>
                  <li>
                    <%= link_to "Cart Page", potepan_cart_page_path %>
                  </li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li>
                    <%= link_to "Step 1 - Shipping", potepan_checkout_step_1_path %>
                  </li>
                  <li>
                    <%= link_to "Step 2 - Payment", potepan_checkout_step_2_path %>
                  </li>
                  <li>
                    <%= link_to "Step 3 - Confirmation", potepan_checkout_step_3_path %>
                  </li>
                  <li>
                    <%= link_to "Order Complete", potepan_checkout_complete_path %>
                  </li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
            <ul class="dropdown-menu dropdown-menu-left">
              <li>
                <%= link_to "About Us", potepan_about_us_path %>
              </li>
              <li>
                <%= link_to "Privacy Policy", potepan_privacy_policy_path %>
              </li>
              <li>
                <%= link_to "Terms &amp; Conditions", potepan_tokushoho_path %>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li>
                <%= link_to "Left Sidebar", potepan_blog_left_sidebar_path %>
              </li>
              <li>
                <%= link_to "Single Left Sidebar", potepan_blog_single_left_sidebar_path %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/potepan/categories/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_root_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_sidebar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <div class="panel panel-default">
    <div class="panel-heading">商品カテゴリー</div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <ul class="nav navbar-nav side-nav">
          <% taxonomies.each do |taxonomy| %>
            <li>
              <%= link_to "javascript:;", data: {toggle: "collapse", target: "#category-#{taxonomy.id}"} do %>
                <%= taxonomy.name %>
                <i class="fa fa-plus"></i>
              <% end %>
              <ul id="category-<%= taxonomy.id %>" class="collapse collapseItem">
                <% taxonomy.root.leaves.each do |leaf| %>
                  <li>
                    <%= link_to potepan_category_path(leaf.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i><%= leaf.name %>
                      <span><%= "(#{leaf.products.all.count})" %></span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">色から探す</div>
    <div class="panel-body">
      <ul class="list-unstyled filter-by-color">
        <% option_types.colors.each do |color| %>
          <li>
            <%= link_to (potepan_category_path(id: taxon.id, option: color.name)) do %>
              <%= color.presentation %><span>(<%= count_products_with_option_value(color) %>)</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">サイズから探す</div>
    <div class="panel-body">
      <ul class="list-unstyled clearfix">
        <% option_types.sizes.each do |size| %>
          <li>
            <%= link_to (potepan_category_path(id: taxon.id, option: size.name)) do %>
              <%= size.presentation %><span>(<%= count_products_with_option_value(size) %>)</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<!-- LIGHT SECTION -->
<%= render 'light_section', taxon: @taxon %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%= render 'sidebar', taxon: @taxon, taxonomies: @taxonomies, option_types: @option_types %>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <%= form_tag(request.path, method: :get, enforce_utf8: false) do %>
              <%= select_tag "sort", options_for_select([
                ["新着順", "arrivals_desc"],
                ["安い順", "low_price"],
                ["高い順", "high_price"],
                ["古い順", "arrivals_asc"]],
                selected: params[:sort] || "arrivals_desc"),
                { class: "select-drop", onchange: "this.form.submit()"} %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <% @products.each do |product| %>
            <div class="col-sm-4 col-xs-12">
              <div class="productBox">
                <%= link_to potepan_product_path(product.id) do %>
                  <div class="productImage clearfix">
                    <%= image_tag(product.display_image.attachment(:large)) %>
                  </div>
                  <div class="productCaption clearfix">
                    <h5><%= product.name %></h5>
                    <h3><%= product.display_price %></h3>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render "shared/partners" %>

app/views/potepan/home/index.html.erb
<% provide(:title, "Home") %>
<!-- BANNER -->
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li>
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
        </li>
      </ul>
    </div>
  </div>
</div>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row featuredCollection">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>人気カテゴリー</h4>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='single_product.html';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-01.jpg", :alt => "feature-collection-image") %>
            <div class="masking">
              <%= link_to "View Shirts", potepan_category_path(id:6), class:"btn viewBtn" %>
            </div>
          </div>
          <div class="caption">
            <h4>Shirts</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='single_product.html';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-02.jpg", :alt => "feature-collection-image") %>
            <div class="masking">
              <%= link_to "View Bags", potepan_category_path(id:3), class:"btn viewBtn" %>
            </div>
          </div>
          <div class="caption">
            <h4>Bags</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='single_product.html';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-03.jpg", :alt => "feature-collection-image") %>
            <div class="masking">
              <%= link_to "View Denim", potepan_category_path(id:1), class:"btn viewBtn" %>
            </div>
          </div>
          <div class="caption">
            <h4>Denim</h4>
          </div>
        </div>
      </div>
    </div>
    <div class="row featuredProducts">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>新着商品</h4>
        </div>
      </div>
      <div class="col-xs-12">
        <div class="owl-carousel featuredProductsSlider">
          <% @new_products.each do |new_product| %>
            <div class="slide">
              <%= link_to potepan_product_path(new_product.id) do %>
                <div class="productImage clearfix">
                  <%= image_tag(new_product.display_image.attachment.url(:large)) %>
                </div>
                <div class="productCaption clearfix">
                  <h5><%= new_product.name %></h5>
                  <h3><%= new_product.display_price %></h3>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render "shared/partners" %>
<!-- PORDUCT QUICK VIEW MODAL -->
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>149円</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/potepan/orders/_line_item.html.erb
<%= order_form.fields_for :line_items, line_item do |line_item_fields| %>
  <tr>
    <td class="col-xs-2">
      <%= link_to potepan_line_item_path(line_item), class: "close", method: :delete  do %>
        <span aria-hidden="true">&times;</span>
      <% end %>
      <span class="cartImage">
        <%= image_tag(line_item.variant.display_image.attachment(:small)) %>
      </span>
    </td>
    <td class="col-xs-4">
      <%= line_item.name %>
    </td>
    <td class="col-xs-2">
      <%= line_item.display_price %>
    </td>
    <td class="col-xs-2">
      <%= line_item_fields.number_field :quantity, min: 0 %>
    </td>
    <td class="col-xs-2">
      <%= line_item.display_total %>
    </td>
  </tr>
<% end %>

app/views/potepan/products/_cart_form.html.erb
<%= form_for :order, url: potepan_line_items_path do |f| %>
  <% if product.variants.any? %>
    <span class="quick-drop">
      <%= select_tag :variant_id, options_from_collection_for_select(
        product.variants, :id, :options_text), class: "select-drop" %>
    </span>
  <% else %>
    <%= hidden_field_tag :variant_id, product.master.id %>
  <% end %>
  <span class="quick-drop resizeWidth">
    <%= select_tag :quantity, options_for_select([*1..5]), class: "select-drop" %>
  </span>
  <div class="btn-area">
    <%= button_tag(type: 'submit', class: 'btn btn-primary btn-block') do %>
    カートに入れる<i class="fa fa-angle-right" aria-hidden="true"></i>
    <% end %>
  </div>
<% end %>

app/views/potepan/products/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_root_path %>
          </li>
          <li class="active"><%= product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% related_products.each do |related_product| %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="productBox">
        <%= link_to potepan_product_path(related_product.id) do %>
          <div class="productImage clearfix">
            <%= image_tag related_product.display_image.attachment(:large) %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= related_product.name %></h5>
            <h3><%= related_product.display_price %></h3>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/products/search.html.erb
<% provide(:title, "Results by Search #{@search_word}") %>
<div class="main-wrapper">
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @search_word %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to "Home", potepan_root_path %>
            </li>
            <li>
              <a href="#">shop</a>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-sm-3 col-xs-12">
            <div class="productBox">
              <%= link_to potepan_product_path(product.id) do %>
                <div class="productImage clearfix">
                  <%= image_tag(product.display_image.attachment(:large)) %>
                </div>
                <div class="productCaption clearfix">
                  <h5><%= product.name %></h5>
                  <h3><%= product.display_price %></h3>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
  <%= render "shared/partners" %>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<!-- LIGHT SECTION -->
<%= render 'light_section', product: @product %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% @product.images.each_with_index do |image, index| %>
                  <div class="item <%= "active" if index.zero? %>" data-thumb="<%= index %>">
                    <%= image_tag(image.attachment.url(:large) ) %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                    <% @product.images.each_with_index do |image, index| %>
                      <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
                        <%= image_tag("#{image.attachment.url(:small)}") %>
                      </div>
                    <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <%= link_to potepan_category_path(@product.taxons.first.id) do %>
                  <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                <% end %>
              </li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <%= render "cart_form", product: @product %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'related_products', related_products: @related_products %>
  </div>
</section>